# inspo: https://github.com/eh8/chenglab/blob/main/.github/workflows/flake.yml

name: Bump flake.lock
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 0

      - uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3

      - run: nix flake update

      - uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d
        with:
          commit_message: "chore(deps): bump flake.lock"
          commit_user_name: Flake Bot
          commit_options: --no-verify --signoff
          commit_author: Flake Bot <actions@github.com>
          branch: main
          file_pattern: flake.lock
          skip_dirty_check: false
          skip_fetch: true
